6 missions page frameworkbarebones
knowOne08/vgec-rocketry-space pull request #35
Opened 2024-08-13 11:39 UTC by Chetan559

Mission page update

2024-08-13 14:27 UTC, knowOne08 commented on apps/frontend/public/Mission.png
make the image as the background, like the video clip in  other pages

2024-08-13 14:31 UTC, knowOne08 commented on apps/frontend/src/app/components/Navbar.tsx
Ese pura delete karke change mat karo change tracking mai problem ho jata hai, it's hard to figure out what has been changed. Next time se dhyan rakhna

2024-08-13 14:32 UTC, knowOne08 commented on apps/frontend/src/app/pages/AboutUs.tsx
Is file mai changes kyu hai bhai ?

Agar pretttier aur esa koi formatting tool use kar rahe ho to mat karo.

2024-08-13 14:34 UTC, knowOne08 commented on package.json
Ye dono remove kar dena agar nahi use kar rahe hai  to.

2024-08-13 14:35 UTC, knowOne08 requested changes
Sahi hai.

Jo bhi changes bataye hai wo dekh ke resovle kar dena jaldi se

2024-08-14 10:54 UTC, Chetan559 commented on apps/frontend/public/Mission.png
done

2024-08-14 10:55 UTC, Chetan559 commented on apps/frontend/src/app/pages/Missions.tsx
done

2024-08-14 10:55 UTC, Chetan559 commented on package.json
yarn.lock k conflicts baki h

2024-08-19 05:05 UTC, merged